# Generated by Django 4.1.2 on 2022-10-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
